// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf74uiorLxZrfrg-6Ydk_5P3jXpC4VTQY',
    appId: '1:854956481023:web:450f853b3143eb73ecefca',
    messagingSenderId: '854956481023',
    projectId: 'chat-app-39970',
    authDomain: 'chat-app-39970.firebaseapp.com',
    storageBucket: 'chat-app-39970.appspot.com',
    measurementId: 'G-H8QLWLVKZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZnjxrbjtzpR9MXLPng0BavkqwAJZtc0',
    appId: '1:854956481023:android:546d203fd9da1b14ecefca',
    messagingSenderId: '854956481023',
    projectId: 'chat-app-39970',
    storageBucket: 'chat-app-39970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN2_CITniDdpRtVXWKBbZNr7Au79o-w5Y',
    appId: '1:854956481023:ios:94e70cad16fdddccecefca',
    messagingSenderId: '854956481023',
    projectId: 'chat-app-39970',
    storageBucket: 'chat-app-39970.appspot.com',
    iosClientId: '854956481023-fd2q3ibsmiavt35nee1idp7vfq5q2tkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
